# Generated by Django 4.1.6 on 2023-02-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='user name')),
                ('username', models.CharField(max_length=32, verbose_name='username')),
            ],
        ),
    ]
