# Generated by Django 4.1.6 on 2023-02-03 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='username',
        ),
    ]
