# Generated by Django 4.1.6 on 2023-02-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_name_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='username')),
                ('invitee', models.CharField(max_length=32, verbose_name='invitee')),
                ('response', models.CharField(max_length=32, verbose_name='response')),
            ],
        ),
    ]
