# Generated by Django 4.1.6 on 2023-02-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='username',
            field=models.CharField(default=None, max_length=32, verbose_name='username'),
        ),
    ]
