# Generated by Django 4.1.6 on 2023-02-04 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_name_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='invitation',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.DeleteModel(
            name='user_info',
        ),
    ]
