# Generated by Django 4.1.6 on 2023-02-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0006_delete_invitation_delete_name_delete_user_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='Username')),
                ('Invitee', models.CharField(max_length=32, verbose_name='Invitee')),
            ],
        ),
    ]
