# Generated by Django 4.1.6 on 2023-02-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation_confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='Username')),
                ('Invitee', models.CharField(max_length=32, verbose_name='Invitee')),
            ],
        ),
    ]
