# Generated by Django 4.1.6 on 2023-02-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_invitation_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation_confirmation',
            name='Response',
            field=models.CharField(default='No', max_length=32, verbose_name='Invitee'),
        ),
    ]
