# Generated by Django 4.1.6 on 2023-02-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_createeventinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createeventinfo',
            name='date',
            field=models.DateField(max_length=32, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='createeventinfo',
            name='sub_event',
            field=models.CharField(max_length=32, verbose_name='sub_event'),
        ),
        migrations.AlterField(
            model_name='createeventinfo',
            name='time',
            field=models.TimeField(max_length=32, verbose_name='time'),
        ),
    ]
